"""
Week 2 Integration Module: Connects embedder.py output to vector_store.py
"""

from typing import List, Dict, Any, Optional
from vector_store import VectorStore

def ingest_embedder_output(
    vector_store: VectorStore,
    ids: List[str],
    chunks: List[str],
    embeddings: List[List[float]],
    metadatas: Optional[List[Dict[str, Any]]] = None
) -> None:
    """
    Validates and integrates embeddings from embedder.py into the VectorStore.

    Args:
        vector_store (VectorStore): Initialized instance of the Week 1 VectorStore.
        ids (List[str]): Unique identifiers for each chunk.
        chunks (List[str]): The text chunks generated by chunker.py.
        embeddings (List[List[float]]): The vector embeddings generated by embedder.py.
        metadatas (Optional[List[Dict[str, Any]]]): Optional metadata for each chunk.

    Raises:
        ValueError: If embeddings are invalid or multi-dimensional constraints fail.
    """
    # 1. Validate embeddings before insertion
    if not embeddings:
        raise ValueError("Embeddings list is empty. Nothing to ingest.")

    # Ensure all embeddings have the exact same dimensionality and correct data types
    expected_dim = len(embeddings[0])
    for i, emb in enumerate(embeddings):
        if not isinstance(emb, list):
            raise ValueError(f"Embedding at index {i} is not a list.")
        if len(emb) != expected_dim:
            raise ValueError(f"Dimension mismatch at index {i}. Expected {expected_dim}, got {len(emb)}.")
        if any(not isinstance(val, (int, float)) for val in emb):
            raise ValueError(f"Embedding at index {i} contains non-numeric values.")

    # 2. Store embeddings and chunks in ChromaDB
    # Delegates to the existing VectorStore implementation (which handles parallel length validation)
    vector_store.upsert_documents(
        ids=ids,
        documents=chunks,
        embeddings=embeddings,
        metadatas=metadatas
    )

def retrieve_similar_chunks(
    vector_store: VectorStore,
    query_embedding: List[float],
    top_k: int = 3
) -> Dict[str, List[Any]]:
    """
    Retrieves stored vectors based on a query embedding using the existing VectorStore.

    Args:
        vector_store (VectorStore): Initialized instance of the Week 1 VectorStore.
        query_embedding (List[float]): The embedded search query.
        top_k (int): Number of top results to retrieve.

    Returns:
        Dict[str, List[Any]]: Dictionary containing ids, documents, metadatas, and distances.
    """
    # Validate query embedding
    if not query_embedding or not isinstance(query_embedding, list):
        raise ValueError("Query embedding must be a non-empty list.")
        
    if any(not isinstance(val, (int, float)) for val in query_embedding):
        raise ValueError("Query embedding must contain only numeric values.")

    # 3. Use existing VectorStore methods to retrieve vectors
    return vector_store.search(query_embedding=query_embedding, top_k=top_k)
