"""
Week 2: Vector Storage Integration Workflow
Handles the efficient batch ingestion of chunks and embeddings into ChromaDB.
"""

from typing import List, Dict, Any, Optional
import time

# Assuming VectorStore is imported from your Week 1 implementation
from vector_store import VectorStore

def store_vectors_efficiently(
    vector_store: VectorStore,
    chunks: List[str],
    embeddings: List[List[float]],
    ids: Optional[List[str]] = None,
    metadatas: Optional[List[Dict[str, Any]]] = None,
    batch_size: int = 100
) -> Dict[str, Any]:
    """
    Efficiently validates, batches, and stores chunks and embeddings into ChromaDB.
    Maintains synchronization between documents, embeddings, and IDs.

    Args:
        vector_store (VectorStore): Initialized Week 1 VectorStore instance.
        chunks (List[str]): Text chunks generated by chunker.py.
        embeddings (List[List[float]]): Vector embeddings generated by embedder.py.
        ids (Optional[List[str]]): Unique identifiers. If None, they are auto-generated.
        metadatas (Optional[List[Dict[str, Any]]]): Optional metadata per chunk.
        batch_size (int): The number of vectors to insert per batch to avoid payload limits.

    Returns:
        Dict[str, Any]: Statistics regarding the insertion process.

    Raises:
        ValueError: If input constraints (lengths, types) are violated.
    """
    start_time = time.time()

    # 1. Ensure IDs, embeddings, and documents remain synchronized
    n_items = len(chunks)
    
    if n_items == 0:
        raise ValueError("The chunks list is empty. Nothing to store.")
        
    if len(embeddings) != n_items:
        raise ValueError(f"Synchronization Error: {n_items} chunks provided, but {len(embeddings)} embeddings provided.")
        
    if metadatas is not None and len(metadatas) != n_items:
        raise ValueError(f"Synchronization Error: {n_items} chunks provided, but {len(metadatas)} metadatas provided.")

    # 2. Auto-generate IDs if not provided, ensuring alignment
    if ids is None:
        ids = [f"chunk_{int(start_time)}_{i}" for i in range(n_items)]
    elif len(ids) != n_items:
        raise ValueError(f"Synchronization Error: {n_items} chunks provided, but {len(ids)} IDs provided.")

    # 3. Validate embeddings data integrity
    expected_dim = len(embeddings[0])
    for i, emb in enumerate(embeddings):
        if not isinstance(emb, list) or len(emb) != expected_dim:
            raise ValueError(f"Embedding at index {i} has invalid dimension or type.")

    # 4. Store efficiently in batches
    stats = {
        "total_attempted": n_items,
        "total_inserted": 0,
        "batches_processed": 0,
        "errors": [],
        "execution_time_seconds": 0.0
    }

    # Process in chunks of `batch_size` to optimize memory and network payload
    for i in range(0, n_items, batch_size):
        batch_ids = ids[i : i + batch_size]
        batch_chunks = chunks[i : i + batch_size]
        batch_embs = embeddings[i : i + batch_size]
        batch_metas = metadatas[i : i + batch_size] if metadatas is not None else None

        try:
            # Leverage existing Week 1 vector store functionality
            vector_store.upsert_documents(
                ids=batch_ids,
                documents=batch_chunks,
                embeddings=batch_embs,
                metadatas=batch_metas
            )
            
            stats["total_inserted"] += len(batch_ids)
            stats["batches_processed"] += 1
            
        except Exception as e:
            error_msg = f"Failed to insert batch {stats['batches_processed'] + 1}: {str(e)}"
            stats["errors"].append(error_msg)
            # We record the error but continue executing remaining batches to ensure partial success

    stats["execution_time_seconds"] = round(time.time() - start_time, 4)
    stats["status"] = "success" if not stats["errors"] else ("partial_success" if stats["total_inserted"] > 0 else "failure")
    
    return stats

def retrieve_vectors(
    vector_store: VectorStore,
    query_embedding: List[float],
    top_k: int = 3
) -> Dict[str, List[Any]]:
    """
    Retrieves the most relevant chunks from ChromaDB based on semantic similarity.
    Designed for seamless integration with the future search_engine.py module.

    Args:
        vector_store (VectorStore): Initialized Week 1 VectorStore instance.
        query_embedding (List[float]): The 1D vector generated from the user's search query.
        top_k (int): Number of top results to retrieve. Defaults to 3.

    Returns:
        Dict[str, List[Any]]: Dictionary containing aligned lists of:
            - 'documents'
            - 'metadatas'
            - 'ids'
            - 'distances' (similarity scores)
            Returns empty lists if the collection is empty.
    """
    # 1. Handle empty collections gracefully
    if vector_store.collection.count() == 0:
        return {
            "ids": [],
            "documents": [],
            "metadatas": [],
            "distances": []
        }

    # 2. Validate input embedding format
    if not query_embedding or not isinstance(query_embedding, list):
        raise ValueError("Query embedding must be a non-empty list of floats.")

    # 3. Retrieve top_k results using existing VectorStore
    # The Week 1 search() method naturally returns the required flattened dict structure
    results = vector_store.search(
        query_embedding=query_embedding,
        top_k=top_k
    )

    return results
